FROM node:20-alpine
RUN corepack enable && corepack prepare pnpm@9 --activate
RUN apk add --no-cache curl
WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm install

COPY . .
RUN npx prisma generate

EXPOSE 3000

CMD ["pnpm", "dev", "--turbopack"]
